export interface MethodDefinition {
	namespace: string
	name: string
	method: string
	httpMethod: 'GET' | 'POST' | 'PUT' | 'DELETE'
	authRequired: boolean
	description: string
}

export const CANONICAL_METHODS: readonly MethodDefinition[] = [
	// Database
	{
		namespace: 'database',
		name: 'getRelease',
		method: 'database.getRelease',
		httpMethod: 'GET',
		authRequired: false,
		description: 'Get a release from the database',
	},
	{
		namespace: 'database',
		name: 'getReleaseRating',
		method: 'database.getReleaseRating',
		httpMethod: 'GET',
		authRequired: true,
		description: "Get a user's rating for a release",
	},
	{
		namespace: 'database',
		name: 'setReleaseRating',
		method: 'database.setReleaseRating',
		httpMethod: 'PUT',
		authRequired: true,
		description: "Set or update a user's rating for a release",
	},
	{
		namespace: 'database',
		name: 'deleteReleaseRating',
		method: 'database.deleteReleaseRating',
		httpMethod: 'DELETE',
		authRequired: true,
		description: "Delete a user's rating for a release",
	},
	{
		namespace: 'database',
		name: 'getReleaseCommunityRating',
		method: 'database.getReleaseCommunityRating',
		httpMethod: 'GET',
		authRequired: false,
		description: 'Get the community rating for a release',
	},
	{
		namespace: 'database',
		name: 'getMaster',
		method: 'database.getMaster',
		httpMethod: 'GET',
		authRequired: false,
		description: 'Get a master release from the database',
	},
	{
		namespace: 'database',
		name: 'getMasterVersions',
		method: 'database.getMasterVersions',
		httpMethod: 'GET',
		authRequired: false,
		description: 'Get all versions of a master release',
	},
	{
		namespace: 'database',
		name: 'getArtist',
		method: 'database.getArtist',
		httpMethod: 'GET',
		authRequired: false,
		description: 'Get an artist profile from the database',
	},
	{
		namespace: 'database',
		name: 'getArtistReleases',
		method: 'database.getArtistReleases',
		httpMethod: 'GET',
		authRequired: false,
		description: 'Get releases and masters by an artist',
	},
	{
		namespace: 'database',
		name: 'getLabel',
		method: 'database.getLabel',
		httpMethod: 'GET',
		authRequired: false,
		description: 'Get a label from the database',
	},
	{
		namespace: 'database',
		name: 'getLabelReleases',
		method: 'database.getLabelReleases',
		httpMethod: 'GET',
		authRequired: false,
		description: 'Get releases associated with a label',
	},
	{
		namespace: 'database',
		name: 'search',
		method: 'database.search',
		httpMethod: 'GET',
		authRequired: true,
		description: 'Search the Discogs database across artists, releases, masters, and labels',
	},

	// Collection
	{
		namespace: 'collection',
		name: 'getFolders',
		method: 'collection.getFolders',
		httpMethod: 'GET',
		authRequired: false,
		description: "Retrieve folders in a user's collection",
	},
	{
		namespace: 'collection',
		name: 'getFolder',
		method: 'collection.getFolder',
		httpMethod: 'GET',
		authRequired: false,
		description: "Retrieve metadata for a specific user's collection folder",
	},
	{
		namespace: 'collection',
		name: 'createFolder',
		method: 'collection.createFolder',
		httpMethod: 'POST',
		authRequired: true,
		description: 'Create a new collection folder',
	},
	{
		namespace: 'collection',
		name: 'updateFolder',
		method: 'collection.updateFolder',
		httpMethod: 'POST',
		authRequired: true,
		description: 'Edit a collection folder name',
	},
	{
		namespace: 'collection',
		name: 'deleteFolder',
		method: 'collection.deleteFolder',
		httpMethod: 'DELETE',
		authRequired: true,
		description: 'Delete a collection folder',
	},
	{
		namespace: 'collection',
		name: 'getCollectionValue',
		method: 'collection.getCollectionValue',
		httpMethod: 'GET',
		authRequired: true,
		description: "Retrieve estimated financial valuation of a user's collection",
	},
	{
		namespace: 'collection',
		name: 'getFields',
		method: 'collection.getFields',
		httpMethod: 'GET',
		authRequired: false,
		description: 'Retrieve custom collection fields configured by a user',
	},
	{
		namespace: 'collection',
		name: 'getReleases',
		method: 'collection.getReleases',
		httpMethod: 'GET',
		authRequired: false,
		description: "View release items in a user's collection folder",
	},
	{
		namespace: 'collection',
		name: 'addRelease',
		method: 'collection.addRelease',
		httpMethod: 'POST',
		authRequired: true,
		description: "Add a release to a user's collection folder",
	},
	{
		namespace: 'collection',
		name: 'deleteRelease',
		method: 'collection.deleteRelease',
		httpMethod: 'DELETE',
		authRequired: true,
		description: "Delete an instance of a release from a user's collection folder",
	},
	{
		namespace: 'collection',
		name: 'editCustomField',
		method: 'collection.editCustomField',
		httpMethod: 'POST',
		authRequired: true,
		description: 'Edit custom field values for a collection release instance',
	},

	// Wantlist
	{
		namespace: 'wantlist',
		name: 'getWantlist',
		method: 'wantlist.getWantlist',
		httpMethod: 'GET',
		authRequired: false,
		description: "Retrieve releases in a user's wantlist",
	},
	{
		namespace: 'wantlist',
		name: 'addRelease',
		method: 'wantlist.addRelease',
		httpMethod: 'PUT',
		authRequired: true,
		description: "Add a release to a user's wantlist",
	},
	{
		namespace: 'wantlist',
		name: 'updateRelease',
		method: 'wantlist.updateRelease',
		httpMethod: 'POST',
		authRequired: true,
		description: "Update notes or rating for a release in a user's wantlist",
	},
	{
		namespace: 'wantlist',
		name: 'deleteRelease',
		method: 'wantlist.deleteRelease',
		httpMethod: 'DELETE',
		authRequired: true,
		description: "Delete a release from a user's wantlist",
	},

	// User
	{
		namespace: 'user',
		name: 'getIdentity',
		method: 'user.getIdentity',
		httpMethod: 'GET',
		authRequired: true,
		description: 'Retrieve identity of the currently authenticated user',
	},
	{
		namespace: 'user',
		name: 'getProfile',
		method: 'user.getProfile',
		httpMethod: 'GET',
		authRequired: false,
		description: "Retrieve a user's public profile",
	},
	{
		namespace: 'user',
		name: 'updateProfile',
		method: 'user.updateProfile',
		httpMethod: 'POST',
		authRequired: true,
		description: "Update the authenticated user's profile metadata",
	},
	{
		namespace: 'user',
		name: 'getSubmissions',
		method: 'user.getSubmissions',
		httpMethod: 'GET',
		authRequired: false,
		description: "Retrieve a user's catalog submissions",
	},
	{
		namespace: 'user',
		name: 'getContributions',
		method: 'user.getContributions',
		httpMethod: 'GET',
		authRequired: false,
		description: "Retrieve a user's catalog contributions",
	},

	// Marketplace
	{
		namespace: 'marketplace',
		name: 'getListing',
		method: 'marketplace.getListing',
		httpMethod: 'GET',
		authRequired: false,
		description: 'View marketplace listing details',
	},
	{
		namespace: 'marketplace',
		name: 'createListing',
		method: 'marketplace.createListing',
		httpMethod: 'POST',
		authRequired: true,
		description: 'Create a new marketplace listing',
	},
	{
		namespace: 'marketplace',
		name: 'updateListing',
		method: 'marketplace.updateListing',
		httpMethod: 'POST',
		authRequired: true,
		description: 'Edit a marketplace listing',
	},
	{
		namespace: 'marketplace',
		name: 'deleteListing',
		method: 'marketplace.deleteListing',
		httpMethod: 'DELETE',
		authRequired: true,
		description: 'Delete a marketplace listing',
	},
	{
		namespace: 'marketplace',
		name: 'getInventory',
		method: 'marketplace.getInventory',
		httpMethod: 'GET',
		authRequired: false,
		description: "View listings in a user's inventory",
	},
	{
		namespace: 'marketplace',
		name: 'getOrder',
		method: 'marketplace.getOrder',
		httpMethod: 'GET',
		authRequired: true,
		description: 'View data associated with an order',
	},
	{
		namespace: 'marketplace',
		name: 'updateOrder',
		method: 'marketplace.updateOrder',
		httpMethod: 'POST',
		authRequired: true,
		description: 'Update the status or shipping of an order',
	},
	{
		namespace: 'marketplace',
		name: 'listOrders',
		method: 'marketplace.listOrders',
		httpMethod: 'GET',
		authRequired: true,
		description: 'List orders for the authenticated user',
	},
	{
		namespace: 'marketplace',
		name: 'getPriceSuggestions',
		method: 'marketplace.getPriceSuggestions',
		httpMethod: 'GET',
		authRequired: true,
		description: 'Retrieve market price suggestions for a release',
	},
	{
		namespace: 'marketplace',
		name: 'getFee',
		method: 'marketplace.getFee',
		httpMethod: 'GET',
		authRequired: false,
		description: 'Calculate Discogs selling fee for a given price',
	},

	// Lists
	{
		namespace: 'lists',
		name: 'getUserLists',
		method: 'lists.getUserLists',
		httpMethod: 'GET',
		authRequired: false,
		description: 'Retrieve public lists created by a user',
	},
	{
		namespace: 'lists',
		name: 'getList',
		method: 'lists.getList',
		httpMethod: 'GET',
		authRequired: false,
		description: 'Retrieve items in a specific user list',
	},

	// Auth
	{
		namespace: 'auth',
		name: 'getRequestToken',
		method: 'auth.getRequestToken',
		httpMethod: 'POST',
		authRequired: true,
		description: 'Request an unauthorized OAuth 1.0a Request Token',
	},
	{
		namespace: 'auth',
		name: 'getAuthorizeUrl',
		method: 'auth.getAuthorizeUrl',
		httpMethod: 'GET',
		authRequired: false,
		description: 'Build user authorization URL for an OAuth Request Token',
	},
	{
		namespace: 'auth',
		name: 'getAccessToken',
		method: 'auth.getAccessToken',
		httpMethod: 'POST',
		authRequired: true,
		description: 'Exchange OAuth Request Token and Verifier for permanent Access Token',
	},
] as const
